app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /
